name: Daily Commit Job

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow
  
jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Make changes to files (example: updating a timestamp)
      - name: Make changes
        run: |
          echo "Last updated on $(date)" > daily-update.txt

      # Configure Git for committing
      - name: Configure Git
        run: |
          git config user.name "abrahamgregorius"
          git config user.email "athioii6@gmail.com"

      # Commit changes
      - name: Commit changes
        run: |
          git add .
          git commit -m "Daily update: $(date)"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push
